version: '3'

networks:
  proxy:
    external:
      name: traefik_proxy
  backend:
    driver: bridge
    internal: true
  database:
    external:
      name: mysql57_backend

services:
  web:
    image: ezitisitis/laravel:7.4
    container_name: placeholder_web
    command: php-fpm7.3 -F
    restart: always
    volumes:
      - .:/app
    labels:
      traefik.enable: "false"
    networks:
      - proxy
      - backend
      - database

  nginx:
    image: nginx:latest
    container_name: placeholder_nginx
    restart: always
    volumes:
      - ./public:/app/public
      - ./storage/app:/app/storage/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx-logs:/var/log/nginx
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.placeholder.entrypoints=http"
      - "traefik.http.routers.placeholder.rule=Host(`placeholder.localhost`,`www.placeholder.localhost`)"
      - "traefik.http.routers.placeholder.middlewares=traefik-https-redirect"
      - "traefik.http.routers.placeholder-secure.entrypoints=https"
      - "traefik.http.routers.placeholder-secure.rule=Host(`placeholder.localhost`,`www.placeholder.localhost`)"
      - "traefik.http.routers.placeholder-secure.tls.certresolver=http"
    networks:
      - proxy
      - backend
