name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build latest image
        run: |
          docker buildx build --push \
            --tag ezitisitis/laravel:latest \
            --platform linux/amd64,linux/arm64/v8 .
      - name: build development image
        run: |
          docker buildx build --push \
            --tag ezitisitis/laravel:development \
            --platform linux/amd64,linux/arm64/v8 . \
            --file=Dockerfile.development
      - name: build npm image
        run: |
          docker buildx build --push \
            --tag ezitisitis/laravel:npm \
            --platform linux/amd64,linux/arm64/v8 . \
            --file=Dockerfile.npm
      - name: build npm-development image
        run: |
          docker buildx build --push \
            --tag ezitisitis/laravel:npm-development \
            --platform linux/amd64,linux/arm64/v8 . \
            --file=Dockerfile.development-npm
